[versions]
h2 = "2.4.240"
kotlin = "2.4.0"
logback = "1.5.35"
postgresql = "42.7.11"
prometheus = "1.17.0"
junit = "6.1.2"
hikari = "7.1.0"
kotliquery = "1.9.1"
flyway = "12.10.0"
googleAuth = "1.49.0"

[libraries]
h2database-h2 = { module = "com.h2database:h2", version.ref = "h2" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
micrometer-registryPrometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "prometheus" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikari = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari" }
kotliquery = { group = "com.github.seratch", name = "kotliquery", version.ref = "kotliquery" }
flyway = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
flyway-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }
google-auth = { group = "com.google.auth", name = "google-auth-library-oauth2-http", version.ref = "googleAuth" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

