package dev.frammenti.fuckumeter.extensions

import kotliquery.LoanPattern.using
import kotliquery.Query
import kotliquery.Session
import java.sql.PreparedStatement
import java.sql.Statement

fun Session.createPreparedStatement(query: Query, returnGeneratedKeys: Boolean = this.returnGeneratedKeys): PreparedStatement {
    val stmt = if (returnGeneratedKeys) {
        if (connection.driverName == "oracle.jdbc.driver.OracleDriver") {
            connection.underlying.prepareStatement(query.cleanStatement, autoGeneratedKeys.toTypedArray())
        } else {
            connection.underlying.prepareStatement(query.cleanStatement, Statement.RETURN_GENERATED_KEYS)
        }
    } else {
        connection.underlying.prepareStatement(query.cleanStatement)
    }

    if (queryTimeout != null) {
        stmt.queryTimeout = queryTimeout!!
    }

    return populateParams(query, stmt)
}

fun Session.insert(query: Query): Long? {
    return using(createPreparedStatement(query, true)) { stmt ->
        if (stmt.executeUpdate() > 0) {
            val rs = stmt.generatedKeys
            rs.next()
            rs.getLong(1)
        } else null
    }
}