ktor:
  deployment:
    port: 8080
  application:
    modules:
      - dev.frammenti.fuckumeter.HttpKt.configureHttp
      - dev.frammenti.fuckumeter.MonitoringKt.configureMonitoring
      - dev.frammenti.fuckumeter.SerializationKt.configureSerialization
      - dev.frammenti.fuckumeter.auth.JwtAuthKt.configureJwtAuth
      - dev.frammenti.fuckumeter.exceptions.StatusPagesKt.configureStatusPages
      - dev.frammenti.fuckumeter.ApplicationKt.module
database:
  url: ${?POSTGRES_URL}
  user: ${?POSTGRES_USER}
  password: ${?POSTGRES_PASSWORD}
jwt:
  issuer: https://fum.frammenti.dev
  audience: fuckumeter-app
  realm: Fuckumeter
  secret: ${?JWT_SECRET}
  accessTokenExpirationSeconds: 300
security:
  refreshTokenSecret: ${?REFRESH_TOKEN_SECRET}
  inviteSecret: ${?INVITE_SECRET}
  inviteEncryptionKey: ${?INVITE_ENCRYPTION_KEY}
