ktor:
  deployment:
    port: 8080
  application:
    modules:
      - dev.frammenti.fuckumeter.HttpKt.configureHttp
      - dev.frammenti.fuckumeter.MonitoringKt.configureMonitoring
      - dev.frammenti.fuckumeter.SerializationKt.configureSerialization
      - dev.frammenti.fuckumeter.security.SecurityKt.configureSecurity
      - dev.frammenti.fuckumeter.db.ModuleKt.initializeDatabase
      - dev.frammenti.fuckumeter.exceptions.StatusPagesKt.configureStatusPages
      - dev.frammenti.fuckumeter.controller.RoutingKt.configureRouting
postgres:
  url: ${?POSTGRES_URL}
  user: ${?POSTGRES_USER}
  password: ${?POSTGRES_PASSWORD}

jwt:
  issuer: Fuckumeter
  audience: fuckumeter-app
  realm: fum.frammenti.dev
  secret: ${?JWT_SECRET}
  accessTokenExpirationSeconds: 300

refreshTokenSecret: ${?REFRESH_TOKEN_SECRET}
inviteSecret: ${?INVITE_SECRET}
inviteEncryptionKey: ${?INVITE_ENCRYPTION_KEY}
